# Generated by Django 5.2 on 2025-04-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
