# Generated by Django 5.2 on 2025-04-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_project_clientlogo_projectimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about",
            name="profile_image",
        ),
        migrations.RemoveField(
            model_name="about",
            name="resume_link",
        ),
        migrations.AddField(
            model_name="about",
            name="available_for_freelance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="about",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="about",
            name="name",
            field=models.CharField(default="Your Name", max_length=100),
        ),
        migrations.AddField(
            model_name="about",
            name="role",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
