# Generated by Django 5.2 on 2025-04-17 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_remove_about_profile_image_remove_about_resume_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about",
            name="name",
        ),
    ]
