# Generated by Django 5.2 on 2025-04-17 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_remove_about_available_for_freelance_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="About",
        ),
    ]
