# Generated by Django 5.2 on 2025-04-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="name",
            field=models.CharField(default="Your Name", max_length=100),
        ),
    ]
