# Generated by Django 5.2 on 2025-04-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0012_skill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="icon_svg",
        ),
        migrations.AddField(
            model_name="skill",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="skill_icons/"),
        ),
    ]
