# Generated by Django 5.2 on 2025-04-21 11:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0013_remove_skill_icon_svg_skill_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="starting_price",
        ),
    ]
