# Generated by Django 5.2 on 2025-04-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0014_remove_skill_starting_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="icon",
            field=models.FileField(blank=True, null=True, upload_to="skill_icons/"),
        ),
    ]
