# Generated by Django 5.2 on 2025-04-22 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0017_blogpost_blogcomment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="banner_image",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="date_posted",
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name="BlogReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="myapp.blogpost",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="BlogComment",
        ),
    ]
