# Generated by Django 5.2 on 2025-04-22 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0018_remove_blogpost_banner_image_blogpost_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="image",
        ),
        migrations.CreateModel(
            name="BlogImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="blog_images/")),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="myapp.blogpost",
                    ),
                ),
            ],
        ),
    ]
