# Generated by Django 5.2 on 2025-04-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0019_remove_blogpost_image_blogimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
        migrations.DeleteModel(
            name="BlogImage",
        ),
    ]
