# Generated by Django 5.2 on 2025-04-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0020_blogpost_image_delete_blogimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_year", models.CharField(max_length=10)),
                ("end_year", models.CharField(max_length=10)),
                ("degree", models.CharField(max_length=255)),
                ("university", models.CharField(max_length=255)),
            ],
        ),
    ]
